### ISSUE TITLE
/feathers

### ISSUE THREAD

**Issue by guohan950106** [RJBeetel3/mimic3_analysis#1]
Hello, Beetel. I cannot find the folder /feathers.   Have you forget to upload it？

**Comment by RJBeetel3** [comment]
I haven't worked on this repo in some time, could you please remind me where the folder /feathers is referenced?

**Comment by guohan950106** [comment]
in ICU_MORTALITY_FIRST24.ipynb
<http://localhost:8888/notebooks/mimic3_analysis-master/ICU_MORTALITY_FIRST24.ipynb>
[image: G1PZ{XZ16HAPGGI3@)FRY78.png]

[image: ]0WVJ2S1_48(U5D5QF}~GV5.png]
I have find out all folders, but I can not find the folder /feathers. As a
result, I cannot run  ICU_MORTALITY_FIRST24.ipynb
<http://localhost:8888/notebooks/mimic3_analysis-master/ICU_MORTALITY_FIRST24.ipynb>.
I hope you can give me any help.

Regards!



Rob Beetel <notifications@github.com> 于2018年12月4日周二 上午2:04写道：

**Comment by RJBeetel3** [comment]
guohan, 
I generated the mimic3 database locally, then generated 3 tables by querying that database, CHART_EVENTS_FIRST24.csv, LAB_EVENTS_FIRST24.csv and PTNT_DEMOG_FIRST24.csv. I then process each of those in their respective notebooks to generate features that are found in the features folder. 
I didn't upload the initial csv tables as they were very large. I am uploading the /features/  folder now. Please let me know if you have any additional issues.
